# Generated by Django 5.2.1 on 2025-05-19 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('назва', models.CharField(max_length=200, verbose_name='Назва опитування')),
                ('опис', models.TextField(blank=True, verbose_name='Опис опитування')),
                ('дата_створення', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('активне', models.BooleanField(default=True, verbose_name='Активне?')),
                ('категорія', models.CharField(choices=[('суспільство', 'Суспільство'), ('технології', 'Технології'), ('освіта', 'Освіта'), ('політика', 'Політика'), ('інше', 'Інше')], default='інше', max_length=50, verbose_name='Категорія')),
                ('дозволено_анонімно', models.BooleanField(default=True, verbose_name='Анонімне голосування?')),
                ('мін_вік', models.PositiveIntegerField(default=18, verbose_name='Мінімальний вік')),
                ('кількість_голосів', models.PositiveIntegerField(default=0, verbose_name='Кількість голосів')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('варіант', models.CharField(max_length=100, verbose_name='Вибраний варіант')),
                ('дата_голосування', models.DateTimeField(auto_now_add=True, verbose_name='Час голосування')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, verbose_name='IP-адреса')),
                ('опитування', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll', verbose_name='Опитування')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
