# Generated by Django 5.2.1 on 2025-05-19 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва опитування')),
                ('description', models.TextField(blank=True, verbose_name='Опис опитування')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне?')),
                ('category', models.CharField(choices=[('society', 'Суспільство'), ('technology', 'Технології'), ('education', 'Освіта'), ('politics', 'Політика'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='Анонімне голосування?')),
                ('min_age', models.PositiveIntegerField(default=18, verbose_name='Мінімальний вік')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Кількість голосів')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, verbose_name='Вибраний варіант')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час голосування')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, verbose_name='IP-адреса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll', verbose_name='Опитування')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    
